project:
  type: website

website:
  title: "Katherine E. Dempsey"
  navbar: 
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects


format:
  html:
    theme: styles.scss
    toc: true



