project:
  type: website

website:
  title: "Katherine E. Dempsey"
  navbar: 
    right:
      - href: index.qmd
        text: Home
        icon: house-heart-fill
      - href: projects.qmd
        text: Projects
        icon: clipboard-data
  page-footer: 
    background: "#bfd3e6"  
    right: Copyright 2025, Katherine E. Dempsey

format:
  html:
    theme: styles.scss
    mainfont: Newsreader 400
    toc: true



